MonashBook-war/src/java/BookController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;
import javax.ejb.EJB;
import javax.faces.context.FacesContext;
import monashbook.ejb.BookService;
import monashbook.models.Book;
import monashbook.models.Patron;
import monashbook.models.Review;

/**
 *
 * @author Liang
 */
@Named(value = "bookController")
@SessionScoped
public class BookController implements Serializable {

    @EJB
    BookService bookService;
    private List<Book> books;
    private List<Book> theDetailBook;
    private Book book;
    private Patron patron;
    private String comments;
    private List<Review> bookReviews;
    private int rating;
    
    public BookController() {
        
    }
    
    public Book getBook() {
        return book;
    }

    public void setBook(Book book) {
        this.book = book;
    }
    
    public String read(Book book) {
        this.book = book;
        return "book.xhtml";
    }
    
    public String setupCreate() {
        book = new Book();
        return "book.xhtml";
    }
    
    public String create() {
        bookService.addBook(book);
        return "index.xhtml";
    }
    
    public String update() {
        bookService.updateBook(book);
        return "index.xhtml";
    }
    
    public String delete(Book book) {
        bookService.deleteBook(book);
        return "index.xhtml";
    }

    public List<Book> getTheDetailBook() {
        return theDetailBook;
    }
    
    public List<Book> getAllBooks() {
        return bookService.getAllBooks();
    }

    public void setTheDetailBook(List<Book> theDetailBook) {
        this.theDetailBook = theDetailBook;
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public int getRating() {
        return rating;
    }

    public void setRating(int rating) {
        this.rating = rating;
    }

    public List<Review> getBookReviews() {
        bookReviews = book.getReviews();
        return bookReviews;
    }

    public void setBookReviews(List<Review> bookReviews) {
        this.bookReviews = bookReviews;
    }
    
    
    public String showBook() {
        FacesContext fc = FacesContext.getCurrentInstance();
        Map<String, String> params = fc.getExternalContext().getRequestParameterMap();
        theDetailBook = new ArrayList<Book>();
        String isbn = params.get("isbn");
        books = new ArrayList<>();
        book = new Book();
        books = bookService.getAllBooks();
        for(int i = 0; i < books.size(); i++) {
            if(books.get(i).getIsbn().equals(isbn)) {
                book = books.get(i);
                theDetailBook.add(book);
            }
        }
        return "book.xhtml";
    }
    
    public void postComments() {
        FacesContext fc = FacesContext.getCurrentInstance();
        LoginController loginController = (LoginController) fc.getELContext().getELResolver().getValue(fc.getELContext(), null, "loginController");
        Map<String, String> params = fc.getExternalContext().getRequestParameterMap();
        String isbn = params.get("isbn");
        theDetailBook = new ArrayList<Book>();
        books = new ArrayList<>();
        book = new Book();
        books = bookService.getAllBooks();
        for(int i = 0; i < books.size(); i++) {
            if(books.get(i).getIsbn().equals(isbn)) {
                book = books.get(i);
                theDetailBook.add(book);
            }
        }
        patron = loginController.getLoginedPatron();
        if(patron == null) {
            loginController.setErrorMessage("Please login to make comments.");
        }else {
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
            Date date = new Date();
            String currentDate = dateFormat.format(date);
            Review review = new Review();
            review.setPatron(patron);
            review.setBook(book);
            review.setCommentDate(currentDate);
            review.setComment(comments);
            review.setRating(rating);
            
            book.getReviews().add(review);
            loginController.getPatronReviews().add(review);
            bookService.addBook(book);
            //bookService.addReview(review);
   
        }
    }
    
}

MonashBook-war/src/java/LoginController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.security.MessageDigest;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.context.FacesContext;
import monashbook.ejb.BookService;
import monashbook.models.Loan;
import monashbook.models.Patron;
import monashbook.models.Review;

/**
 *
 * @author Liang
 */
@Named(value = "loginController")
@SessionScoped
public class LoginController implements Serializable {
    @EJB
    BookService bookService;
    private List<Patron> patrons;
    private Patron loginedPatron;
    private String email;
    private String password;
    private String hashedPassword;
    private String rePassword;
    private String name;
    private String phone;
    private String errorMessage;
    private String signUpErrorMessage;
    public LoginController() {
        
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getHashedPassword() {
        return hashedPassword;
    }

    public void setHashedPassword(String hashedPassword) {
        this.hashedPassword = hashedPassword;
    }
    
    public String getRePassword() {
        return rePassword;
    }

    public void setRePassword(String rePassword) {
        this.rePassword = rePassword;
    }
    
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }
    
    public String getErrorMessage() {
        return errorMessage;
    }

    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    public String getSignUpErrorMessage() {
        return signUpErrorMessage;
    }

    public void setSignUpErrorMessage(String signUpErrorMessage) {
        this.signUpErrorMessage = signUpErrorMessage;
    }
    
    public Patron getLoginedPatron() {
        return loginedPatron;
    }

    public void setLoginedPatron(Patron loginedPatron) {
        this.loginedPatron = loginedPatron;
    }
    
    public List<Loan> getPatronLoans() {
        return loginedPatron.getLoans();
    }
    
    public List<Patron> getPatrons() {
        return bookService.getAllPatrons();
    }
    
    public List<Review> getPatronReviews() {
        return loginedPatron.getReviews();
    }
    
    public String loginClick() {
        loginedPatron = new Patron();
        patrons = bookService.getAllPatrons();
        String url = "index.xhtml";
        FacesContext context = FacesContext.getCurrentInstance();
        context.getExternalContext().getSessionMap().put("email", email);
        patrons = bookService.getAllPatrons();
        // Hash the input password into SHA-256 format
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            md.update(password.getBytes());
            byte byteData[] = md.digest();
 
            //convert the byte to hex format method 1
            StringBuffer sb = new StringBuffer();
            for (int i = 0; i < byteData.length; i++) {
             sb.append(Integer.toString((byteData[i] & 0xff) + 0x100, 16).substring(1));
             hashedPassword = sb.toString();
            }
        }
        catch(Exception e) {
            System.out.println("MessageDigest Error.");
        }
        
        for(Patron p:patrons){
            if(p.getEmail().equals(email) && p.getPassword().equals(hashedPassword)) {
                loginedPatron = p;
                errorMessage = "You have already logined.";
                url = "index.xhtml";
            }else if(p.getEmail().equals(email) && !p.getPassword().equals(hashedPassword)){
                loginedPatron = null;
                errorMessage = "Invalid password, please re-enter.";
                url = "login.xhtml";
            }else if(p.getPassword().equals(hashedPassword) && !p.getEmail().equals(email)) {
                loginedPatron = null;
                errorMessage = "Invalid email, please re-enter.";
                url = "login.xhtml";
            }else {
                loginedPatron = null;
                errorMessage = "Invalid email and password, please re-enter.";
                url = "login.xhtml";
            }
        }
        return url;
    }
    public String signUp() {
        // Hash the input password into SHA-256 format
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            md.update(password.getBytes());
            byte byteData[] = md.digest();
 
            //convert the byte to hex format method 1
            StringBuffer sb = new StringBuffer();
            for (int i = 0; i < byteData.length; i++) {
             sb.append(Integer.toString((byteData[i] & 0xff) + 0x100, 16).substring(1));
             hashedPassword = sb.toString();
            }
        }
        catch(Exception e) {
            System.out.println("MessageDigest Error.");
        }
        
        
        String url = "index.xhtml";
        if(loginedPatron == null){
            loginedPatron = new Patron();
            if(name.equals("")){
                signUpErrorMessage = "Name can not be empty.";
                url = "registration.xhtml";
            }else if(email.equals("")) {
                signUpErrorMessage = "Email can not be empty.";
                url = "registration.xhtml";
            }else if(phone.equals("")) {
                signUpErrorMessage = "Phone number can not be empty.";
                url = "registration.xhtml";
            }else if(password.equals("")) {
                signUpErrorMessage = "Password can not be empty.";
                url = "registration.xhtml";
            }else if(!password.equals(rePassword)) {
                signUpErrorMessage = "Passwords do not match.";
                url = "registration.xhtml";
            }else {
                loginedPatron.setPassword(hashedPassword);
                loginedPatron.setEmail(email);
                loginedPatron.setName(name);
                loginedPatron.setPhone(phone);
                bookService.addPatron(loginedPatron);
                errorMessage = "You have already logined.";
                url = "index.xhtml";
            }
        }
        return url;
    }
}

MonashBook-war/web/adminLogin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Administration Login</title>
    </h:head>
    <h:body>
        <ui:composition template="admin/master.xhtml">
            <ui:define name="content">
            <h2 style="text-align: center;">Administration Login</h2>
            <hr></hr>
            <div id="adminLoginInput">
                <form method="POST" action="j_security_check">
                    <label for="j_username">Username:</label>
                    <input class="form-control" type="text" name="j_username" />
                    <label for="j_password">Password:</label>
                    <input class="form-control" type="password" name="j_password" />
                    <input class="btn btn-primary" type="submit" value="Submit"/>
                </form>
            </div>
        </ui:define>
        </ui:composition>
    </h:body>
</html>

MonashBook-war/web/book.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Book Details</title>
    </h:head>
    <h:body>
        <ui:composition template="master.xhtml">
            <ui:define name="content">
                <div id="bookDetailSection">
                    <h2><h:outputText value="Book Details"/></h2>
                    <hr></hr>
                    <h:outputText value="#{bookController.showBook()}" style="display: none" />
                    <ui:repeat var="theBook" value="#{bookController.theDetailBook}">
                        <div id="bookLargeImg">
                            <img src="#{theBook.imageUrl}"></img>
                        </div>
                        <div id="bookDetails">
                            <h3><h:outputText value="#{theBook.title}"/></h3>
                            <p><h:outputText value="by #{theBook.author}"/></p>
                            <p><h:outputText value="ISBN: #{theBook.isbn}"/></p>
                            <p><h:outputText value="Publisher: #{theBook.publisher}"/></p>
                            <p><h:outputText value="Publish date: #{theBook.publishDate}"/></p>
                            <p>Description: </p>
                            <p><h:outputText value="#{theBook.description}"/></p>
                            <h:form>
                                <h:commandLink class="btn btn-primary" action="#{loanController.makeLoan()}" rendered="#{theBook.availability eq true and not empty loginController.loginedPatron}">
                                    Make Loan
                                    <f:param name="isbn" value="#{theBook.isbn}"></f:param>
                                </h:commandLink>
                            
                                <h:link class="btn btn-primary disabled" rendered="#{theBook.availability eq false}">Not Available</h:link>
                                &nbsp;&nbsp;
                                <h:commandLink class="btn btn-warning" action="#{loanController.bookmarkBook()}" rendered="#{not empty loginController.loginedPatron}" >
                                    <span class="glyphicon glyphicon-bookmark"></span>Bookmark
                                    <f:param name="isbn" value="#{theBook.isbn}"></f:param>
                                </h:commandLink><br></br>
                            </h:form>
                            <br></br>
                            <b><h:outputText value="Login to make a loan or leave comments." rendered="#{empty loginController.loginedPatron}"></h:outputText></b>
                            <h:form>
                                <h:panelGroup rendered="#{not empty loginController.loginedPatron}">
                                    <p>Add a comment:</p>
                                    <h:inputTextarea class="form-control" rows="4" value="#{bookController.comments}"></h:inputTextarea><br></br>
                                    <h:commandLink class="btn btn-info btn-sm" action="#{bookController.postComments()}">
                                        Post
                                        <f:param name="isbn" value="#{theBook.isbn}"></f:param>
                                    </h:commandLink>
                                </h:panelGroup>
                            </h:form>
                        </div>
                        <div class="clear">
                            <p></p>
                        </div>
                        <hr></hr>
                        <h4>Comments</h4>
                        <p><h:outputText value="No comments." rendered="#{empty theBook.reviews}"></h:outputText></p>
                        <ui:repeat var="review" value="#{theBook.reviews}">
                            <div class="panel panel-info">
                                <div class="panel-heading">
                                  <p>
                                      <h:outputText value="#{review.patron.name}"></h:outputText>
                                      <h:outputText value=" on #{review.commentDate}"></h:outputText>
                                  </p>
                                </div>
                                <div class="panel-body">
                                  <h:outputText value="#{review.comment}"></h:outputText>
                                </div>
                              </div>
                        </ui:repeat>
                    </ui:repeat>
                    
                    
                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

MonashBook-war/web/category.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough">
    <h:head>
        <title>#{indexController.categoryPageTitle}</title>
    </h:head>
    <h:body>
        <ui:composition template="master.xhtml">
            <ui:define name="content">
                <div id="bookShow">
                    <h2><h:outputText value="#{indexController.categoryPageTitle}"/></h2>
                    <ui:repeat var="book" value="#{indexController.categoryBooks}" varStatus="status">
                        <div class="bookThumb">
                            <h:form>
                                <h:commandLink action="#{bookController.showBook()}">
                                    <img class="bookSmallImg" src="#{book.imageUrl}"></img>
                                    <h5><h:outputText value="#{book.title}"/></h5>
                                    <f:param name="isbn" value="#{book.isbn}" />
                                </h:commandLink>
                            </h:form>
                            <h:outputText value="by #{book.author}"/><br></br>
                            <h:outputText value="ISBN: #{book.isbn}"/>
                        </div>
                    </ui:repeat>
                </div>
                <div id="sideBar">
                    <h:form>
                        <h:inputText class="searchText form-control" value="#{indexController.searchQuery}" p:placeholder="title, author or isbn"/>
                        <h:commandButton class="btn btn-primary" action="search.xhtml" value="Search">
                        </h:commandButton>
                        </h:form>
                    <div class="clear">
                        <p></p>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">News &amp; Events</h3>
                        </div>
                        <div class="panel-body">
                            <p><span class="glyphicon glyphicon-hand-right"></span> Access all databases through our new databases guide</p>
                            <p><span class="glyphicon glyphicon-hand-right"></span> Quick study guides - tips for exams, essays</p>
                            <p><span class="glyphicon glyphicon-hand-right"></span> Changes to access over exam study period</p>
                            <p><span class="glyphicon glyphicon-hand-right"></span> What's new: Monash Books Management System</p>
                            <p><span class="glyphicon glyphicon-hand-right"></span> Fair Use proposal: how your teaching and research will benefit</p>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">Opening Hours</h3>
                        </div>
                        <div class="panel-body">
                            <p><b>Sunday: </b>10am-9pm</p>
                            <p><b>Monday: </b>8am-12midnight</p>
                            <p><b>Tuesday: </b>8am-12midnight</p>
                            <p><b>Wednesday: </b>8am-12midnight</p>
                            <p><b>Thursday: </b>8am-12midnight</p>
                            <p><b>Friday: </b>8am-12midnight</p>
                            <p><b>Saturday: </b>10am-9pm</p>
                        </div>
                    </div>
                </div>
                
                <div class="clear">
                    <p></p>
                </div>  
            </ui:define>
        </ui:composition>
    </h:body>
</html>

MonashBook-war/web/error.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Login Error</title>
    </h:head>
    <h:body>
        <ui:composition template="admin/master.xhtml">
            <ui:define name="content">
            <h2 style="text-align: center;">Authentication Error</h2>
            <hr></hr>
            <p style="text-align: center; color: #FF0000;">The user credentials you have supplied are incorrect.</p>
            <p style="text-align: center;">Please attempt to <h:link outcome="adminLogin" value="login" /> again.</p>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

MonashBook-war/web/userProfile.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Personal Profile</title>
    </h:head>
    <h:body>
        <ui:composition template="master.xhtml">
            <ui:define name="content">
                <h2>Welcome, <h:outputText value="#{profileController.patron.name}"/></h2>
                <hr></hr>
                <div class="panel panel-default">
                    <div class="panel-heading">
                      <h3 class="panel-title">Your personal detail</h3>
                    </div>
                    <div class="panel-body">
                      <div id="personalDetail">
                          <p><b>Email: </b><h:outputText value="#{profileController.patron.email}"/></p>
                          <p><b>Phone number: </b><h:outputText value="#{profileController.patron.phone}"/></p>
                    </div>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                      <h3 class="panel-title">Your loan history</h3>
                    </div>
                    <div class="panel-body">
                        
                                
                        <p><h:outputText value="#{profileController.loanMessage}" rendered="#{empty profileController.loanedBooks}"></h:outputText></p>
                        <ui:repeat var="loan" value="#{profileController.loans}" varStatus="status">
                            <div class="panel panel-default">
                            <div class="panel-body">
                                
                                
                                <div id="theLoanInfo">
                                    <b>Loan Date: </b><h:outputText value="#{loan.loanDate}"></h:outputText>
                                        <b>Due date: </b><h:outputText value="#{loan.dueDate}"/> &nbsp;
                                        <h:outputText class="label label-info" value="#{loan.status}"/>
                                        <h:form>
                                            <h:commandLink style="float: right;" rendered="#{loan.book.availability eq false}" action="#{profileController.returnBook()}" class="btn btn-success btn-xs">
                                                Return Book
                                                <f:param name="date" value="#{loan.loanDate}" />
                                                <f:param name="isbn" value="#{loan.book.isbn}" />
                                            </h:commandLink>
                                        </h:form>
                                </div>
                                    <div class="clear"><p></p></div>
                                    <hr></hr>
                                
                                <div id="loanBookSection">
                                    <div id="smallLoanBookImg">
                                        <img class="bookSmallImg" src="#{loan.book.imageUrl}"></img>
                                    </div>
                                    <div id="loanBookInfo">
                                        <h5><h:outputText value="#{loan.book.title}"/></h5>
                                        <p><h:outputText value="by #{loan.book.author}"/></p>
                                        <p><b>ISBN: </b><h:outputText value="#{loan.book.isbn}"/></p>
                                        <p><b>Publisher: </b><h:outputText value="#{loan.book.publisher}"/></p>
                                        <p><b>Publish date: </b><h:outputText value="#{loan.book.publishDate}"/></p>
                                        <p><b>Description: </b></p>
                                        <p><h:outputText value="#{loan.book.description}"/></p>
                                    </div>
                                    <div class="clear"><p></p></div>
                                    
                                </div>
                            </div>
                            </div>
                        </ui:repeat>
                    </div>
                  </div>
                    

                <div class="panel panel-default">
                    <div class="panel-heading">
                      <h3 class="panel-title">Your bookmarks</h3>
                    </div>
                    <div class="panel-body">
                        <p><h:outputText value="#{profileController.bookmarkMessage}" rendered="#{empty profileController.markedBooks}"></h:outputText></p>
                        <ui:repeat var="book" value="#{profileController.markedBooks}" varStatus="status">
                        <div class="panel panel-default">
                            <div class="panel-body">
                              <div id="markedBookSection">
                                  <div id="smallLoanBookImg">
                                      <img class="bookSmallImg" src="#{book.imageUrl}"></img>
                                  </div>
                                  <div id="markedBookInfo">
                                    <h4><h:outputText value="#{book.title}"/></h4>
                                    <p><h:outputText value="by #{book.author}"/></p>
                                    <p><b>ISBN: </b><h:outputText value="#{book.isbn}"/></p>
                                    <p><b>Publisher: </b><h:outputText value="#{book.publisher}"/></p>
                                    <p><b>Publish date: </b><h:outputText value="#{book.publishDate}"/></p>
                                    <p><b>Description: </b></p>
                                    <p><h:outputText value="#{book.description}"/></p>
                                  </div>
                              </div>
                            </div>
                        </div>
                        </ui:repeat>
                    </div>
                  </div>
                    
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <h3 class="panel-title">Your reviews</h3>
                    </div>
                    <div class="panel-body">
                        <p><h:outputText value="#{profileController.reviewMessage}" rendered="#{empty profileController.patronReviews}"></h:outputText></p>
                        <ui:repeat var="review" value="#{profileController.patronReviews}" varStatus="status">
                        <div class="panel panel-default">
                            <div class="panel-body">
                              <div id="markedBookSection">
                                  <div id="smallReviewBookImg">
                                      <img class="reviewBookSmallImg" src="#{review.book.imageUrl}"></img>
                                      <p><b><h:outputText value="#{review.book.title}"/></b></p>
                                  </div>
                                  <div id="reviewBookInfo">
                                    <p><b>Comment date: </b><h:outputText value="#{review.commentDate}"/></p>
                                    <p><b>Comment: </b><h:outputText value="#{review.comment}"></h:outputText></p>
                                  </div>
                              </div>
                            </div>
                        </div>
                        </ui:repeat>
                    </div>
                  </div>
                
            </ui:define>
        </ui:composition>
    </h:body>
</html>