MonashBook-war/src/java/BookController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;
import javax.ejb.EJB;
import javax.faces.context.FacesContext;
import monashbook.ejb.BookService;
import monashbook.models.Book;
import monashbook.models.Patron;
import monashbook.models.Review;

/**
 *
 * @author Liang
 */
@Named(value = "bookController")
@SessionScoped
public class BookController implements Serializable {

    @EJB
    BookService bookService;
    private List<Book> books;
    private List<Book> theDetailBook;
    private Book book;
    private Patron patron;
    private String comments;
    private List<Review> bookReviews;
    private int rating;
    
    public BookController() {
        
    }
    
    public Book getBook() {
        return book;
    }

    public void setBook(Book book) {
        this.book = book;
    }
    
    public String read(Book book) {
        this.book = book;
        return "book.xhtml";
    }
    
    public String setupCreate() {
        book = new Book();
        return "book.xhtml";
    }
    
    public String create() {
        bookService.addBook(book);
        return "index.xhtml";
    }
    
    public String update() {
        bookService.updateBook(book);
        return "index.xhtml";
    }
    
    public String delete(Book book) {
        bookService.deleteBook(book);
        return "index.xhtml";
    }

    public List<Book> getTheDetailBook() {
        return theDetailBook;
    }
    
    public List<Book> getAllBooks() {
        return bookService.getAllBooks();
    }

    public void setTheDetailBook(List<Book> theDetailBook) {
        this.theDetailBook = theDetailBook;
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public int getRating() {
        return rating;
    }

    public void setRating(int rating) {
        this.rating = rating;
    }

    public List<Review> getBookReviews() {
        bookReviews = book.getReviews();
        return bookReviews;
    }

    public void setBookReviews(List<Review> bookReviews) {
        this.bookReviews = bookReviews;
    }
    
    
    public String showBook() {
        FacesContext fc = FacesContext.getCurrentInstance();
        Map<String, String> params = fc.getExternalContext().getRequestParameterMap();
        theDetailBook = new ArrayList<Book>();
        String isbn = params.get("isbn");
        books = new ArrayList<>();
        book = new Book();
        books = bookService.getAllBooks();
        for(int i = 0; i < books.size(); i++) {
            if(books.get(i).getIsbn().equals(isbn)) {
                book = books.get(i);
                theDetailBook.add(book);
            }
        }
        return "book.xhtml";
    }
    
    public void postComments() {
        FacesContext fc = FacesContext.getCurrentInstance();
        LoginController loginController = (LoginController) fc.getELContext().getELResolver().getValue(fc.getELContext(), null, "loginController");
        Map<String, String> params = fc.getExternalContext().getRequestParameterMap();
        String isbn = params.get("isbn");
        theDetailBook = new ArrayList<Book>();
        books = new ArrayList<>();
        book = new Book();
        books = bookService.getAllBooks();
        for(int i = 0; i < books.size(); i++) {
            if(books.get(i).getIsbn().equals(isbn)) {
                book = books.get(i);
                theDetailBook.add(book);
            }
        }
        patron = loginController.getLoginedPatron();
        if(patron == null) {
            loginController.setErrorMessage("Please login to make comments.");
        }else {
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
            Date date = new Date();
            String currentDate = dateFormat.format(date);
            Review review = new Review();
            review.setPatron(patron);
            review.setBook(book);
            review.setCommentDate(currentDate);
            review.setComment(comments);
            review.setRating(rating);
            
            book.getReviews().add(review);
            loginController.getPatronReviews().add(review);
            bookService.addBook(book);
            //bookService.addReview(review);
   
        }
    }
    
}

MonashBook-war/web/admin/book.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough">
    <h:head>
        <title>Edit/Add Books</title>
    </h:head>
    <h:body>
        <ui:composition template="master.xhtml">
            <ui:define name="content">
                <h:form>
                    <h2 style="text-align: center;">Edit/Add Books</h2>
                    <hr></hr>
                    <div class="errorAlert">
                        <b><h:outputText class="editBookErrorMessage" value="#{loginController.signUpErrorMessage}" rendered="#{empty loginController.loginedPatron}"></h:outputText></b>
                    </div>
                    <div id="editBookInput">
                        <table id="editBookTb">
                            <tr>
                                <td class="tdtitle">Title:</td>
                                <td class="tdvalue"><h:inputText class="form-control bookTitleInput" value="#{bookController.book.title}" title="Title" p:placeholder="title"></h:inputText></td>
                            </tr>
                            <tr>
                                <td class="tdtitle">Author:</td>
                                <td class="tdvalue"><h:inputText class="form-control bookAuthorInput" value="#{bookController.book.author}" title="Author" p:placeholder="author"></h:inputText></td>
                            </tr>
                            <tr>
                                <td class="tdtitle">ISBN:</td>
                                <td class="tdvalue"><h:inputText class="form-control bookIsbnInput" value="#{bookController.book.isbn}" title="ISBN" p:placeholder="book isbn"></h:inputText></td>
                            </tr>
                            <tr>
                                <td class="tdtitle">Publisher:</td>
                                <td class="tdvalue"><h:inputText class="form-control bookPublisherInput" value="#{bookController.book.publisher}" title="Publisher" p:placeholder="publisher"></h:inputText></td>
                            </tr>
                            <tr>
                                <td class="tdtitle">Publish Date:</td>
                                <td class="tdvalue">
                                    <div class="input-append date" id="datepicker" data-date-format="dd/mm/yyyy">
                                        <h:inputText size="16" disabled="true" class="form-control calendarInput" value="#{bookController.book.publishDate}"></h:inputText>
                                        <span class="add-on"><span class="glyphicon glyphicon-calendar"></span></span>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td class="tdtitle">Description:</td>
                                <td class="tdvalue"><h:inputTextarea class="form-control bookDescInput" rows="4" value="#{bookController.book.description}" title="Description" p:placeholder="description"></h:inputTextarea></td>
                            </tr>
                            <tr>
                                <td class="tdtitle">ImageUrl:</td>
                                <td class="tdvalue"><h:inputText class="form-control" value="#{bookController.book.imageUrl}" title="ImageUrl" p:placeholder="image url"></h:inputText></td>
                            </tr>
                            <tr>
                                <td class="tdtitle">Availability:</td>
                                <td class="tdvalue">
                                    <h:selectOneMenu class="form-control" value="#{bookController.book.availability}" >
                                        <f:selectItem itemValue="True" itemLabel="Available" />
                                        <f:selectItem itemValue="False" itemLabel="Unavailable" />
                                    </h:selectOneMenu>
                                </td>
                            </tr>
                            
                        </table>
                        <h:panelGroup rendered="#{not empty bookController.bookReviews}">
                            <p>Comments:</p>
                            <ui:repeat var="review" value="#{bookController.bookReviews}" varStatus="status">
                                <p>by <h:outputText value="#{review.patron.name}"></h:outputText></p>
                                <h:inputTextarea class="form-control" value="#{review.comment}"></h:inputTextarea>
                            </ui:repeat>
                            <br></br>
                        </h:panelGroup>
                        <div id="editAddBtn">
                            <h:commandButton value="Cancel" class="btn btn-default" action="index.xhtml"></h:commandButton>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <h:commandButton id="update" value="Update" class="btn btn-primary updateBtn" rendered="#{not empty bookController.book.id}" action="#{bookController.update()}"></h:commandButton>
                            <h:commandButton id="create" value="Create" class="btn btn-primary createBtn" rendered="#{empty bookController.book.id}" action="#{bookController.create()}"></h:commandButton>
                        </div>
                    </div>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

MonashBook-war/web/admin/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Book Management</title>
    </h:head>
    <h:body>
        <ui:composition template="master.xhtml">
            <ui:define name="content">
                <h2>Book Management</h2>
                <hr></hr>
                <h:form>
                    <h:commandButton style="float: right;" class="btn btn-primary btn-xs" action="#{bookController.setupCreate()}" value="Add Book"></h:commandButton>
                <h:dataTable class="table table-striped" value="#{bookController.allBooks}" var="book">
                    <h:column>
                        <f:facet name="header">
                          <h:outputText value="Id"/>
                    </f:facet>
                        <h:outputText value="#{book.id}"/>
                  </h:column>
                    <h:column>
                        <f:facet name="header">
                          <h:outputText value="Title"/>
                    </f:facet>
                        <h:outputText value="#{book.title}"/>
                  </h:column>
                    <h:column>
                        <f:facet name="header">
                          <h:outputText value="Author"/>
                    </f:facet>
                        <h:outputText value="#{book.author}"/>
                  </h:column>
                    <h:column>
                        <f:facet name="header">
                          <h:outputText value="ISBN"/>
                    </f:facet>
                        <h:outputText value="#{book.isbn}"/>
                  </h:column>
                    <h:column>
                        <f:facet name="header">
                          <h:outputText value="Publisher"/>
                    </f:facet>
                        <h:outputText value="#{book.publisher}"/>
                  </h:column>
                    <h:column>
                        <f:facet name="header">
                          <h:outputText value="Publish Date"/>
                    </f:facet>
                        <h:outputText value="#{book.publishDate}"/>
                  </h:column>
                    <h:column>
                        <f:facet name="header">
                          <h:outputText value="Description"/>
                    </f:facet>
                        <h:outputText value="#{book.description}"/>
                  </h:column>
                    <h:column>
                        <f:facet name="header">
                          <h:outputText value="ImageUrl"/>
                        </f:facet>
                        <h:outputText value="#{book.imageUrl}"/>
                  </h:column>
                    <h:column>
                        <f:facet name="header">
                          <h:outputText value="Availability"/>
                        </f:facet>
                        <h:outputText value="#{book.availability}"/>
                  </h:column>
                    <h:column>
                        <f:facet name="header">
                          <h:outputText value=""/>
                        </f:facet>
                        <h:commandButton class="btn btn-success btn-xs" action="#{bookController.read(book)}" value="Edit"></h:commandButton><br></br>
                        <h:commandButton class="btn btn-danger btn-xs" action="#{bookController.delete(book)}" value="Delete"></h:commandButton>
                  </h:column>
                </h:dataTable>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

MonashBook-war/web/admin/master.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title></title>
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css"></link>
        <link rel="stylesheet" type="text/css" href="../resources/css/main.css"></link>
        <link rel="stylesheet" href="../resources/css/datepicker.css"></link>
        <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
        <script src="../resources/js/main.js"></script>
        <script src="../resources/js/bootstrap-datepicker.js"></script>
    </h:head>
    <h:body>
        <div id="header">
            <div id="signBtn">
                <a href="../index.xhtml" style="float: right;" class="btn btn-primary btn-xs">Back to Home</a>
                
            </div>
            <div class="clear"><p></p></div>
            <h1>Monash Books</h1>
        </div>
        <div id="wrapper">
            <div id="content">
                <ui:insert name="content">
                    
                </ui:insert>
            </div>
        </div>
        <div id="footer">
            Monash Books Copyright &copy; 2013. Designed and Developed by Yingliang Zhang
        </div>
        
    </h:body>
</html>